name: First Workflow
on: workflow_dispatch 
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
            echo "Primer hola"
            echo "Segundo hola"
      - name: Print goodbye
        run: echo "ByeWorld"
